// app/src/components/MetricsBlocks/Filter/Filters.tsx
import { Divider, Select } from "antd";
import React from "react";

import css from './Filter.css'
import { getTimeFilterList, getRealVal } from './utils'
import { ClockCircleOutlined } from "@ant-design/icons";
import moment from "moment";
import classNames from "classnames";

type ValueForSelect = {
  database?: string[]
  table?: string[]
  time?: number | string | undefined
  queryKind?: string[]
  type?: string[]
  initialUser?: string[]
}

type Props = {
  databasesList?: {name: string}[]
  tablesList?: {name: string}[]
  typeList?: {name: string}[]
  initialUserList?: {name: string}[]
  queryKindList?: {name: string}[]
  value: ValueForSelect,
  onChange: (obj: ValueForSelect, option?: any) => void,
  updateAllList?: number
}

export const Filter: React.FC<Props> = (props) => {
  const timeFilterList = getTimeFilterList()
  const {
    databasesList,
    tablesList,
    value: { database, table, time, type, queryKind, initialUser },
    onChange,
    typeList,
    initialUserList,
    queryKindList
  } = props
  return <section className={classNames(css.filter, 'filter-dorpdown-fender-container')}>
    { databasesList && <>
        <span className={css.filterTip}>Database</span>
        <Select value={database} dropdownClassName={'light-dropdown'} onChange={(val: string[]) => {
          // const realVal = getRealVal(val)
          onChange({ database: val, table, time })
        }} showArrow style={{ width: 120 }} bordered={false}>
          {
            databasesList.map((item, i) => {
              return <Select.Option key={item.name + i} value={item.name}>{item.name}</Select.Option>
            })
          }
        </Select>
        <Divider type='vertical' />
      </>
    }
    { tablesList && <>
        <span className={css.filterTip}>Table</span>
        <Select value={table} dropdownClassName={'light-dropdown'} onChange={val => {
          // const realVal = getRealVal(val)
          onChange({ database, table: val, time })
        }} showArrow style={{ width: 120 }} bordered={false}>
          {
            tablesList.map(item => {
              return <Select.Option key={item.name} value={item.name}>{item.name}</Select.Option>
            })
          }
        </Select>
        <Divider type='vertical' />
      </>
    }
    { queryKindList && <>
        <span className={css.filterTip}>Query kind</span>
        <Select value={queryKind} dropdownClassName={'light-dropdown'} onChange={val => {
          // const realVal = getRealVal(val)
          onChange({ queryKind: val, type, initialUser, time })
        }} showArrow style={{ width: 120 }} bordered={false}>
          {
            queryKindList.map(item => {
              return <Select.Option key={item.name} value={item.name}>{item.name}</Select.Option>
            })
          }
        </Select>
        <Divider type='vertical' />
      </>
    }
    { typeList && <>
        <span className={css.filterTip}>Query status</span>
        <Select value={type} dropdownClassName={'light-dropdown'} onChange={val => {
          // const realVal = getRealVal(val)
          onChange({ queryKind, type: val, initialUser, time })
        }} showArrow style={{ width: 120 }} bordered={false}>
          {
            typeList.map(item => {
              return <Select.Option key={item.name} value={item.name}>{item.name}</Select.Option>
            })
          }
        </Select>
        <Divider type='vertical' />
      </>
    }
    { initialUserList && <>
        <span className={css.filterTip}>User</span>
        <Select value={initialUser} dropdownClassName={'light-dropdown'} onChange={val => {
          // const realVal = getRealVal(val)
          onChange({ queryKind, type, initialUser: val, time })
        }} showArrow style={{ width: 120 }} bordered={false}>
          {
            initialUserList.map(item => {
              return <Select.Option key={item.name} value={item.name}>{item.name}</Select.Option>
            })
          }
        </Select>
        <Divider type='vertical' />
      </>
    }
    <ClockCircleOutlined className={css.filterIcon} />
    <Select defaultValue={time} dropdownClassName={'light-dropdown'} onChange={(val) => {
      const option = timeFilterList.find(item => item.value === val)
      if (databasesList) {
        onChange({ database, table, time: val }, option)
      } else {
        onChange({ queryKind, type, initialUser, time: val }, option)
      }
    }} showArrow style={{ width: 150 }} bordered={false}>
      {
        timeFilterList.map(item => {
          return <Select.Option key={item.name} value={item.value}>{item.name}</Select.Option>
        })
      }
    </Select>
  </section>
}

// src/components/metrics/filter/Filters.vue
<script lang='ts' setup>
import { onBeforeMount, reactive, ref } from 'vue'
import { Clock } from '@element-plus/icons-vue'
import { getTimeFilterList, queryListWithKey } from './utils'
import { CommonObj } from '../types'
import dayjs from 'dayjs'

type Option = {
  name: string,
  value: string
}

const emit = defineEmits(['change'])

const props = withDefaults(defineProps<{
  selectType?: ('database' | 'table' | 'type' | 'queryKind' | 'user')[]
}>(), {
  selectType: () => ['database', 'table']
})

const databaseList = ref<Option[]>([])
const tableList = ref<Option[]>([])
const queryKindList = ref<Option[]>([])
const typeList = ref<Option[]>([])
const initialUserList = ref<Option[]>([])

const keyList = {
  database: databaseList,
  table: tableList,
  queryKind: queryKindList,
  type: typeList,
  user: initialUserList
}

const defaultValue = reactive({
  database: 'All',
  table: 'All',
  queryKind: 'All',
  user: 'All',
  type: 'All',
  time: dayjs.duration(24, 'hours').asMilliseconds()
})

const timeFilterList = getTimeFilterList()

const getTablesByDatabase = (val: string) => {
  queryListWithKey.table(val)
    .then(res => {
      tableList.value = [
        {name: 'All'},
        ...res.data.map((item: CommonObj) => ({ name: item.name }))
      ]
    })
}

onBeforeMount(() => {
  const { selectType } = props
  Promise.all(selectType.map(type => {
    return queryListWithKey[type]()
  }))
    .then(res => {
      selectType.forEach((type, i) => {
        const data = [
          {name: 'All'},
          ...res[i].data.map((item: CommonObj) => {
            const { type, query_kind, initial_user, name } = item
            return {
              name: name || type || query_kind || initial_user
            }
          })
        ]
        keyList[type].value = data
      })
    })
})
</script>
<template>
  <section class="filter-container">
    <template v-if="selectType.includes('database')">
      <span class="filter-tip">{{ $t('Database') }}</span>
      <el-select
        v-model="defaultValue.database"
        class="m-2"
        placeholder="Select"
        size="small"
        @change="(val: string) => {
          getTablesByDatabase(val)
          emit('change', { database: val })
        }"
      >
        <el-option
          v-for="item in databaseList"
          :key="item.name"
          :label="item.name"
          :value="item.name"
        />
      </el-select>
      <el-divider direction="vertical" />
    </template>
    <template v-if="selectType.includes('table')">
      <span class="filter-tip">{{ $t('Table') }}</span>
      <el-select
        v-model="defaultValue.table"
        class="m-2"
        placeholder="Select"
        size="small"
        @change="(val: string) => {
          emit('change', { table: val })
        }"
      >
        <el-option
          v-for="item in tableList"
          :key="item.name"
          :label="item.name"
          :value="item.name"
        />
      </el-select>
      <el-divider direction="vertical" />
    </template>
    <template v-if="selectType.includes('queryKind')">
      <span class="filter-tip">{{ $t('Query kind') }}</span>
      <el-select
        v-model="defaultValue.queryKind"
        class="m-2"
        placeholder="Select"
        size="small"
        @change="(val: string) => {
          emit('change', { queryKind: val })
        }"
      >
        <el-option
          v-for="item in queryKindList"
          :key="item.name"
          :label="item.name"
          :value="item.name"
        />
      </el-select>
      <el-divider direction="vertical" />
    </template>
    <template v-if="selectType.includes('type')">
      <span class="filter-tip">{{ $t('Query status') }}</span>
      <el-select
        v-model="defaultValue.type"
        class="m-2"
        placeholder="Select"
        size="small"
        @change="(val: string) => {
          emit('change', { type: val })
        }"
      >
        <el-option
          v-for="item in typeList"
          :key="item.name"
          :label="item.name"
          :value="item.name"
        />
      </el-select>
      <el-divider direction="vertical" />
    </template>
    <template v-if="selectType.includes('user')">
      <span class="filter-tip">{{ $t('User') }}</span>
      <el-select
        v-model="defaultValue.user"
        class="m-2"
        placeholder="Select"
        size="small"
        @change="(val: string) => {
          emit('change', { user: val })
        }"
      >
        <el-option
          v-for="item in initialUserList"
          :key="item.name"
          :label="item.name"
          :value="item.name"
        />
      </el-select>
      <el-divider direction="vertical" />
    </template>
    <el-icon><Clock /></el-icon>
    <el-select
      v-model="defaultValue.time"
      class="m-2"
      placeholder="Select"
      size="small"
      @change="(val: string | number) => {
        emit('change', {
          time: val,
          option: timeFilterList.find(item => item.value === val)
        })
      }"
    >
      <el-option
        v-for="item in timeFilterList"
        :key="item.name"
        :label="item.name"
        :value="item.value"
      />
    </el-select>
  </section>
</template>
<style lang='scss' scoped>
.filter-container {
  display: flex;
  justify-content: right;
  align-items: center;
  width: 100%;
  height: 36px;
  padding-right: 10px;
  margin-bottom: 10px;
  background-color: #F0F0F0;
  border: 1px solid #E2E2E2;
  box-sizing: border-box;

  .el-select {
    margin-left: 10px;
  }
}
.filter-tip {
  color: rgba(62, 62, 69, 0.45);
}
</style>
